import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import "../styles/globals.css"
import { Inter, Courgette } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });
const courgette = Courgette({ 
  weight: '400',
  subsets: ['latin'],
  variable: '--font-courgette',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${courgette.variable}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
